version: "3"

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list
    silent: true

  new:article:
    desc: Create a new blog article under src/content/blog
    dir: "{{.ROOT_DIR}}/src/content/blog"
    cmds:
      - note-cli create article -a Junichi.Y --no-dir -t .
    silent: true
